#!/bin/bash

# === Global variables === #
MAIN_PWD=$(pwd)
USER_HOME="/home/$USER"

# === Hiding cursor === #
tput civis

# === Banner === #
source script/00-banner.sh

# === Ctrl + C === #
source script/05-ctrl_c.sh

# === Sudo privileges === #
source script/10-privileges.sh

# === GRUB Configuration === #
source script/20-grub.sh

# === Official Packages Installation === #
source script/30-pacman.sh

# === AUR Packages Installation === #
source script/40-aur.sh

# === From Source Programs Installation === #
source script/50-bento4.sh
source script/53-gef.sh
source script/56-logiops.sh

# === Dotfiles Configuration === #
source script/60-zsh.sh
source script/61-xorg.sh
source script/62-qtile.sh
source script/63-kitty.sh
source script/64-picom.sh
source script/65-ranger.sh
source script/66-rofi.sh
source script/67-wallpapers.sh
source script/68-chromium.sh

# === End === #
source script/70-end.sh
