#!/bin/bash

# === Ctrl + C === #
function ctrl_c {
  echo "\n\n[!] Exiting...\n"
  tput cnorm; exit 1
}
trap ctrl_c INT

# === Hiding cursor === #
tput civis


# === Logging function === #
function log {
  echo "$1\n"; sleep 2
}


# === Banner === #
bash ./assets/banner.sh


# === GRUB Theme === #
log "[*] Configuring GRUB Theme..."
cp -r /usr/share/Pingu/config/CyberRe /usr/share/grub/themes/CyberRe
log "[+] GRUB Theme Configured!"


# === Package installation === #


# === ZSH === #
sleep 1


# === Powerlevel10k === #
sleep 1


# === Qtile === #


# === Neovim - NvChad === #
log "[?] Checking if Neovim is installed..."
if [ command -v nvim &>/dev/null ]; then
  log "[+] Neovim detected! ($(which nvim))"
else
  log "[-] Neovim not installed, installing now..."
  pacman -S nvim --noconfirm &>/dev/null
  log "[+] Neovim installed! ($(which nvim))"
fi

log "[*] Configuring NvChad for Neovim..."
git clone https://github.com/NvChad/NvChad /home/$(logname)/.config/nvim --depth 1 &>/dev/null && nvim
log "[+] NvChad Configured!"
