#!/bin/bash

ctrl_c () {
  echo -e "\n[!] Exiting..."
  exit 1
}
trap ctrl_c INT

if [[ $(echo $PWD | sed -ne 's/^.*pingu//p') != "/assets/tools" ]]; then
  echo -e "\n[!] Run from: pingu/assets/tools\n    Usage: ./downloader"; exit 1
fi
sudo cat /dev/null

if [[ "$1" == "0" ]]; then
  echo -e "[0] Downloading Cross-Toolchain PKGs...\n"
  pushd ../../.. &>/dev/null && mkdir tools && cd $_
  for line in $(cat ../pingu/assets/pkgs/lfs/0-cross_toolchain_pkgs); do
    ver=$(echo $line | awk -F',' '{print $2}')
    line=$(echo $line | sed "s/@/$ver/g")
    pkg=$(echo $line | awk -F',' '{print $1}')
    url=$(echo $line | awk -F',' '{print $3}')
    sig=$(echo $line | awk -F',' '{print $4}' | tr -d '\r')
    
    # mkdir $pkg && cd $_
    echo "  GET      $pkg"
    wget -q "$url"
    # wget -q "$sig"
    # url_file=$(echo $url | rev | cut -d '/' -f 1 | rev)
    # sig_file=$(echo $sig | rev | cut -d '/' -f 1 | rev)
    # gpg --verify $sig_file $url_file || rm *
    # cd .. && rmdir $pkg 2>/dev/null
  done
  popd &>/dev/null
fi
