#!/bin/bash

ctrl_c () {
  echo -e "\n[!] Exiting..."
  exit 1
}
trap ctrl_c INT

if [[ $(echo $PWD | sed -ne 's/^.*pingu//p') != "/assets/tools" ]]; then
  echo -e "\n[!] Run from: pingu/assets/tools\n    Usage: ./downloader"
fi
sudo cat /dev/null

if [[ "$1" -eq "0" ]]; then
  echo -e "[0] Downloading Cross-Toolchain PKGs...\n"
  pushd ../../.. && mkdir tools && cd $_
  for line in $(cat ../pkgs/lfs/0-cross_toolchain_pkgs); do
    ver=$(echo $line | awk '{print $2}')
    line=$(echo $line | sed "s/@/$ver/g")
    pkg=$(echo $line | awk '{print $1}')
    url=$(echo $line | awk '{print $3}')
    sig=$(echo $line | awk '{print $4}')
    echo "  WGET      $pkg"
    wget -q "$url"
    wget -q "$sig"
  done
  popd
fi
