#!/bin/sh

# === Init scripts === #
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# === Load user settings === #
[ -f ~/.Xresources ] && xrdb ~/.Xresources
[ -f ~/.xprofile ] && . ~/.xprofile
[ -f ~/.Xmodmap ] && (sleep 5; xmodmap ~/.Xmodmap) &

# === Start WM === #
exec dbus-run-session i3
