#!/bin/sh

# === Init scripts === #
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# === Importing Xresources file === #
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# === Importing xprofile === #
[ -f ~/.xprofile ] && . ~/.xprofile

# === Starting Window Manager === #
exec dbus-launch --exit-with-session i3
