#!/bin/bash

DIR="/usr/share/lockscreen"
ASSETS="$DIR/assets"
CACHE="$ASSETS/cache"

# === Taking screenshot === #
sleep 0.5
scrot $CACHE/base.png

# === Processing the image === #
# Blurring
convert $CACHE/base.png -blur 0x8 $CACHE/blurred.png
# 'GNU Love' overlay (main monitor)
composite -gravity center -geometry +732+145 $ASSETS/gnu-love.png $CACHE/blurred.png $CACHE/overlayed_1.png
# 'Flying GNU' overlay (second monitor)
composite -gravity southwest -geometry +50+600 $ASSETS/flying-gnu.png $CACHE/overlayed_1.png $CACHE/overlayed_2.png
# Locked indicator (main monitor)
composite -gravity north -geometry +535+330 $ASSETS/lock.png $CACHE/overlayed_2.png $CACHE/overlayed_3.png
# Locked indicator (second monitor)
composite -gravity northwest -geometry +450+11 $ASSETS/lock.png $CACHE/overlayed_3.png $DIR/lockscreen.png

# === Locking the screen with i3lock === #
i3lock -e -i $DIR/lockscreen.png

# === When unlocked, remove all image files used === #
rm $CACHE/*
rm $DIR/lockscreen.png
